/* This file is automatically generated according to button2.xml */
#include <xinu.h>

devcall button2read(struct dentry *devptr, char *buffer, int32 count) {

	if(count!=1) {
		return 0;
	}

	unsigned int baseaddress =  *((unsigned int*)(&devptr->dvcsr));

	GPIO1ModuleClkConfig();
	GPIOModuleEnable(baseaddress);
	GPIOModuleReset(baseaddress);
	GPIO1PinMuxSetup(14);
	GPIODirModeSet(baseaddress, 14, GPIO_DIR_INPUT);

	int r = GPIOPinRead(baseaddress, 14);
	if(r==0)
	{
		buffer[0]='0';
	}
	else
	{
		buffer[0]='1';
	}

	return 1;
}
